import styles from '@/styles/pages/blog.module.scss';
import Layout from '../components/headerAndFooter/Layout';
import BlogSidebar from '@/components/BlogSidebar';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBlog } from '@fortawesome/free-solid-svg-icons';
import BlogContent from '@/components/BlogContent';


const content = [
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Five Pillars of Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "Core practices of Islam: declaration of faith, prayer, almsgiving, fasting, and pilgrimage, guiding Muslim worship and ethics.",
    "link": "/FivePillarsIslam"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Life of Prophet Muhammad",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "The final prophet, whose life and teachings in the Sunnah and Hadiths provide moral and spiritual guidance for Muslims.",
    "link": "/ProphetMuhammadLife"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Quran",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "The holy book of Islam, containing Allah's revelations to Prophet Muhammad, offering comprehensive guidance for all aspects of life.",
    "link": "/TheQuran"
  },
  {
    date: '13',
    time: 'MAY',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Online Quran Memorization Classes',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'Whenever Quran memorization is discussed, issues come to mind: How do you m...',
    link: '/onlineQuranMemorizationClasses',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Teaching the Quran to kids lays the foundation for a lifetime connection with Islam, a journey...`,
    link: '/TeachingQuranToKids',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Why Learn Arabic Language Online',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/LearnArabicOnline',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Online Quran Classes USA',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `You're looking for a way to deepen your connection with the Quran, whether it's for yourself or your child. However, busy schedules and...`,
    link: '/OnlineQuranClassesUSA',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Online Quran Classes for Ladies',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Online Quran classes for ladies: Tajweed, memorization, Islamic studies. Diverse`,
    link: '/OnlineQuranClassesLadies',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn Quran Recitation Online',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Learn Quran recitation online. Flexible classes, expert teachers, and tail...`,
    link: '/LearnQuranRecitationOnline',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Quran Reading Classes for Kids and Adults',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Discover the transformative power of Quran reading classes for kids and ad...`,
    link: '/QuranReadingClasses',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Duas of Ramadan and Rules of Fasting',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Will you keep fasting in the coming Ramadan 2024? Here is the complete guide to understanding the month of Ramadan, its holiness, rules...`,
    link: '/DuasOfRamadanAndRulesOfFasting',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn to Read Quran Online',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Our hectic routines these days make it impossible to devote some time to the Book of Allah (SWT). Each day, we rush off to work or get ...`,
    link: '/LearnToReadQuranOnline',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn Noorani Qaida in Urdu',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `If you plan to enroll yourself or your kids in online Quran classes, the ...`,
    link: '/LearnNooraniQaidaInUrdu',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn Quran Tajweed With Rules',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Table of Contents What is Tajweed? Essential Rules for Quran Recitation Correct Pronunciation Pauses and Stops Intonation a...`,
    link: '/LearnQuranTajweedWithRules',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Prepare For Ramadan',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Table of Contents Ramadan is Approaching! Mentally Prepare For Ramadan Set Realistic Goals Practice Mindfulness to prepar...`,
    link: '/PrepareForRamadan',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Foundation Of Islam: Uunderstand And Learn The',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `The Pillars of Islam are the essential acts of worship and foundational principles that shape a Muslim's daily life and spiritual journ...`,
    link: '/FoundationOfIslam',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Importance of Tafseer in Understanding Quran',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `The Quran is a beautiful tapestry consisting of words that were divinely revealed. However, its intricate threads can be challenging fo...`,
    link: '/TafseerImportance',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Guidelines for Newly Converted Muslims:',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Islam's meteoric rise can be attributed to its following by people from diverse backgrounds. The simplicity and clarity of its teaching...`,
    link: '/NewlyConvertedMuslimsGuidelines',
  },

  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Why Online Quran Education for Kids is Better than',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Religious Significance for Muslims Quran education is essential in Muslim societies. It is a divine revelation and the literal word of...`,
    link: '/OnlineQuranEducationForKids',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn Quran Online with Kamran Institute for Islamic study',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `The best among you are those who learn the Qur'an and teach it – Holy Prophet SAW Table of Contents Importance of Quran Education ...`,
    link: '/LearnQuranWithKamran',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Guide – New Muslims to Learn Quran',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Why should the New Muslims Learn the Quran Online? Learning the Quran is a lifelong journey for Muslims, and it can be challenging fo...`,
    link: '/GuideForNewMuslims',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Learn the Holy Quran in an easy way –',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `“The best among you is the one who learns the Qur’an and teaches it.” Sahih Bukhari Volume 6, Book 61, Number 546: Narrated by Uthma...`,
    link: '/LearnQuranInEasyWay',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Quran Memorization Tips by Kamran Institute for Islamic study',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `The Importance of the Quran Memorization Spiritual Rewards: Memorizing Quran is a highly virtuous act in Islam. Muslims believe th...`,
    link: '/QuranMemorizationTips',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Online Quran learning for beginners by',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Why onlinemadrasa.org? Learning the Quran, the holy book of Islam, is a profound and spiritual...`,
    link: '/OnlineQuranLearningForBeginners',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Al Istikharah',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Al Istikharah – Istakhara Dua Dua for Istakhara or seeking Allah’s council, is a Sunnah way to seek guidance from Allah SWT. We can do...`,
    link: '/AlIstikharahGuide',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Month of Shawwal',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Hadith on Fasting in the Month of Shawwal In the Islamic calendar, the moon of the eleventh month brings joy and happiness to Muslims ...`,
    link: '/ShawwalMonthGuide',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'What is Hajj?',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `Significance of Hajj According to the Quran and Sunnah Hajj season is ahead. Every year, millions of Muslims visit the house of Allah ...`,
    link: '/HajjGuide',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Islamic Art: A Journey Through Culture and Creativity',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A study of the history and elements of Islamic art, including calligraphy, architecture, and visual arts, and how they reflect Islamic beliefs and cultural diversity.',
    link: '/IslamicArtGuide'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Women in Islam: Empowerment and Misconceptions',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An analysis of women\'s rights in Islam, their social and spiritual roles, and common misconceptions surrounding their status in Muslim societies.',
    link: '/WomenInIslam'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'The History and Significance of Ramadan',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An overview of Ramadan\'s historical origins, its spiritual and physical benefits, and the significance of fasting in Islamic faith.',
    link: '/HistoryOfRamadan'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Jihad in Islam: Dispelling Myths and Misunderstandings',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A detailed examination of the concept of Jihad, its various interpretations, and addressing common misunderstandings in the contemporary context.',
    link: '/JihadInIslam'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Sufism: The Mystical Path of Islam',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An introduction to Sufism, its history, key figures, practices, and how it represents the mystical dimension of Islam.',
    link: '/Sufism'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Halal Industry: Ethics and Economics',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A look into the principles of Halal, its importance in Islamic dietary laws, and its impact on global economics and trade.',
    link: '/HalalIndustry'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'The Role of Islamic Finance in Modern Economy',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An analysis of Islamic finance principles, including interest-free banking, and its relevance and application in today\'s global economy.',
    link: '/IslamicFinance'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'The Importance of Education in Islam',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A discussion on the emphasis Islam places on knowledge and education, historical contributions to various fields, and the role of educational institutions in Muslim societies.',
    link: '/EducationInIslam'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Environmental Ethics in Islamic Teachings',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An exploration of how Islamic teachings advocate for environmental stewardship and sustainable living, and their relevance in modern ecological challenges.',
    link: '/EnvironmentalEthics'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Islamic Contributions to Science and Civilization',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A review of significant scientific and cultural contributions made by Muslim scholars during the Islamic Golden Age and their lasting impact on global civilization.',
    link: '/ContributionsToScience'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Sharia Law: Principles and Application',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'A comprehensive look at Sharia law, its sources, principles, and how it is applied in various contexts and countries.',
    link: '/ShariaLaw'
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Interfaith Dialogue: Building Bridges between Islam and other Religions',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'An exploration of the importance of interfaith dialogue, historical and modern examples, and how it fosters understanding and peace between different religious communities.',
    link: '/InterfaithDialogue'
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamophobia: Challenges and Responses in a Global Context",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of the origins and impact of Islamophobia, its effects on Muslim communities worldwide, and strategies for combating prejudice and discrimination.",
    "link": "/Islamophobia"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Diversity of Muslim Cultures: A Global Perspective",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the cultural diversity within the Muslim world, including different traditions, customs, and practices from various regions.",
    "link": "/MuslimCultures"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Ethics in Business and Governance",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of Islamic ethical principles in business and governance, including honesty, fairness, and social responsibility.",
    "link": "/IslamicEthics"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Jihad: Peaceful Struggle or Violent Ideology?",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A nuanced discussion on the various interpretations of Jihad, emphasizing its spiritual and peaceful aspects versus the misconceptions of it being solely a violent struggle.",
    "link": "/ConceptOfJihad"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Eschatology: Understanding the End Times",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic beliefs regarding the end times, including signs of the Last Day, the Day of Judgment, and the afterlife.",
    "link": "/IslamicEschatology"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Human Rights in Islamic Law: Balancing Tradition and Modernity",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of human rights within Islamic law, exploring how traditional principles are balanced with modern human rights frameworks.",
    "link": "/IslamicHumanRights"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Tawheed: Oneness of God in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A detailed look at the central Islamic belief in the oneness of God (Tawheed), its theological implications, and its significance in Muslim worship and daily life.",
    "link": "/ConceptOfTawheed"
  },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Zakat: The Obligatory Charity in Islam",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "An examination of Zakat, its rules, purposes, and the social and economic benefits of this form of obligatory charity in Muslim communities.",
      "link": "/Zakat"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Islamic Calligraphy: Beauty and Devotion in Art",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "A study of the art of Islamic calligraphy, its history, styles, and how it reflects devotion and spirituality in Islamic culture.",
      "link": "/IslamicCalligraphy"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Fatwa: Understanding Islamic Legal Opinions",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "An explanation of what a fatwa is, the process of issuing one, and its role and impact in guiding Muslims in various aspects of life.",
      "link": "/IslamicFatwa"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Islamic Feminism: Reinterpreting Gender Roles and Rights",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "A discussion on Islamic feminism, its goals, methodologies, and how it seeks to reinterpret traditional gender roles and advocate for women's rights within an Islamic framework.",
      "link": "/IslamicFeminism"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "The Significance of Friday (Jumu'ah) in Islam",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "An exploration of the importance of Friday in Islam, the congregational prayers (Jumu'ah), and the associated spiritual and communal benefits.",
      "link": "/FridaySignificance"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "The Concept of Taqwa: God-Consciousness in Islam",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "An examination of Taqwa, its meaning, significance, and how Muslims strive to cultivate this sense of God-consciousness in their lives.",
      "link": "/ConceptOfTaqwa"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "The Legacy of Islamic Golden Age: Science, Philosophy, and Culture",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "A review of the achievements of the Islamic Golden Age, focusing on advancements in science, philosophy, and cultural developments.",
      "link": "/IslamicGoldenAge"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Islamic Ethics in Medical Practice",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "A discussion on the principles of Islamic medical ethics, including issues such as end-of-life care, reproductive ethics, and the use of medical technology.",
      "link": "/IslamicMedicalEthics"
    },
    {
      "date": "13",
      "time": "May",
      "smallHeading": "QURAN EDUCATION",
      "mainHeading": "Dua: The Power of Supplication in Islam",
      "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
      "name": "BINSAADI.COM",
      "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
      "description": "An exploration of the practice of Dua (supplication), its importance, various forms, and the spiritual benefits of calling upon God in times of need and gratitude.",
      "link": "/IslamicDua"
    },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Family Structure in Islam: Rights and Responsibilities",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the family unit in Islam, the roles and responsibilities of each member, and the importance of maintaining family ties and values.",
    "link": "/FamilyStructureIslam"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Importance of Sunnah in Islamic Law and Practice",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A detailed look at the role of Sunnah (the practices of Prophet Muhammad) in shaping Islamic law and guiding daily practices.",
    "link": "/ImportanceOfSunnah"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islam and Modernity: Negotiating Tradition and Change",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of how Muslims navigate the relationship between traditional Islamic values and the demands of modern life, including issues such as technology, fashion, and social norms.",
    "link": "/IslamModernity"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Environmentalism: Preserving Nature as a Religious Duty",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic teachings on environmental conservation, including the concept of stewardship (Khilafah) and practical applications for sustainable living.",
    "link": "/IslamicEnvironmentalism"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Eschatology: Beliefs About the Afterlife",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on Islamic beliefs about life after death, including the soul's journey, the resurrection, and descriptions of paradise and hell.",
    "link": "/IslamicEschatologyAfterlife"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Imams and Scholars in Islamic Communities",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the roles, responsibilities, and influence of Imams and Islamic scholars in guiding and supporting Muslim communities.",
    "link": "/ImamsScholarsRole"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Psychology: Understanding the Mind from an Islamic Perspective",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic approaches to psychology, including concepts of mental health, treatment methods, and the integration of spirituality in psychological well-being.",
    "link": "/IslamicPsychology"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Education: Past, Present, and Future",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A review of the history of Islamic education, its current state, and future challenges and opportunities in providing education within an Islamic framework.",
    "link": "/IslamicEducation"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islam and Humanitarian Aid: Principles and Practices",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of the principles of humanitarian aid in Islam, including charitable giving, disaster relief, and social welfare, and their impact on global humanitarian efforts.",
    "link": "/IslamicHumanitarianAid"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Mysticism: Exploring the Depths of Spiritual Experience",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on Islamic mysticism (Tasawwuf), its practices, key figures, and how it seeks to deepen the spiritual experience and connection with God.",
    "link": "/IslamicMysticism"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Hadith Literature: Preserving the Words and Deeds of Prophet Muhammad",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of Hadith literature, its compilation, classification, and the importance of Hadith in understanding the teachings and practices of Prophet Muhammad.",
    "link": "/HadithLiterature"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Architecture: Reflecting Faith in Design and Structure",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of Islamic architecture, its distinctive features, historical evolution, and how it embodies Islamic principles and aesthetics.",
    "link": "/IslamicArchitecture"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Ihsan: Striving for Excellence in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Ihsan, its meaning, significance in Islamic spirituality, and how Muslims aim to achieve excellence in worship and conduct.",
    "link": "/ConceptOfIhsan"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Women Scholars in Islamic History",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A detailed look at the contributions of women scholars in Islamic history, their achievements, and their impact on various fields of knowledge.",
    "link": "/WomenScholars"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Bioethics: Ethical Considerations in Medicine and Biotechnology",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of bioethical issues in Islam, including genetic engineering, cloning, and medical treatments, and the ethical frameworks used to address these issues.",
    "link": "/IslamicBioethics"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Jurisprudence: Schools of Thought and Legal Interpretation",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An overview of the various schools of thought in Islamic jurisprudence (Fiqh), their methodologies, and their influence on legal interpretation and practice.",
    "link": "/IslamicJurisprudence"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Philanthropy: Charity and Social Welfare in Muslim Societies",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the principles and practices of Islamic philanthropy, including Zakat, Sadaqah, and Waqf, and their role in promoting social welfare.",
    "link": "/IslamicPhilanthropy"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Evolution of Islamic Governance: Caliphate to Modern Nation-State",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the historical evolution of Islamic governance, from the early caliphates to contemporary nation-states, and the challenges and opportunities in modern political systems.",
    "link": "/IslamicGovernance"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Revivalism Movements: Ideologies and Impact",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of various Islamic revivalist movements, their ideologies, goals, and their impact on Muslim societies and global politics.",
    "link": "/IslamicRevivalism"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Ummah: Unity and Diversity in the Muslim Community",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the concept of Ummah, its significance in promoting unity among Muslims, and how it accommodates cultural and regional diversity within the global Muslim community.",
    "link": "/ConceptOfUmmah"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Calendar: Significance and Major Events",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An overview of the Islamic lunar calendar, its significance, and the major religious events and festivals it marks.",
    "link": "/IslamicCalendar"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Al-Quds (Jerusalem) in Islamic Faith",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of the religious and historical significance of Jerusalem (Al-Quds) in Islam, including its connection to the Prophet Muhammad’s Night Journey and its importance to Muslim identity.",
    "link": "/AlQudsRole"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Political Thought: Theory and Practice",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of Islamic political theories, historical examples of Islamic governance, and their relevance to contemporary political systems.",
    "link": "/IslamicPoliticalThought"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Family Law: Marriage, Divorce, and Custody",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of Islamic family law, its principles regarding marriage, divorce, and child custody, and how these laws are applied in different Muslim-majority countries.",
    "link": "/IslamicFamilyLaw"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Mosques in Muslim Communities",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of the role of mosques, not just as places of worship, but as community centers, educational institutions, and places of social gathering.",
    "link": "/MosqueRole"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Fitrah: Innate Disposition in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the concept of Fitrah, the innate disposition towards faith and righteousness in every human, and its implications for moral and spiritual development.",
    "link": "/ConceptOfFitrah"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Views on Animal Rights and Welfare",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic teachings on the treatment of animals, the rights and welfare of animals, and the ethical considerations for Muslims.",
    "link": "/IslamicAnimalRights"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Qur'an: Structure, Themes, and Interpretation",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the structure of the Qur'an, its major themes, and the various methodologies used in its interpretation (Tafsir).",
    "link": "/QuranInterpretation"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading":"QURAN EDUCATION",
    "mainHeading": "The Life and Legacy of Prophet Muhammad",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A comprehensive overview of the life of Prophet Muhammad, his teachings, and his lasting impact on Muslim faith and practice.",
    "link": "/ProphetMuhammad"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Festivals and Celebrations",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of the major Islamic festivals and celebrations, such as Eid al-Fitr and Eid al-Adha, their religious significance, and cultural variations.",
    "link": "/IslamicFestivals"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Influence of Islamic Philosophy on Western Thought",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of the influence of Islamic philosophy on Western intellectual traditions, including the transmission of knowledge through medieval Europe.",
    "link": "/IslamicPhilosophyInfluence"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Youth in Islamic Movements",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the involvement and impact of youth in various Islamic movements, both historical and contemporary, and their role in shaping the future of Muslim societies.",
    "link": "/YouthRoleIslamicMovements"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Jurisprudence on International Relations",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic principles governing international relations, including issues of war and peace, treaties, and diplomatic conduct.",
    "link": "/IslamicInternationalRelations"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Gender Equality",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on Islamic teachings related to gender equality, the roles of men and women, and contemporary interpretations and debates.",
    "link": "/IslamicGenderEquality"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Mysticism and Modern Spirituality",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the relevance and appeal of Islamic mysticism (Sufism) in the modern world, including its practices and philosophical teachings.",
    "link": "/IslamicMysticism"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Economics: Principles and Practices",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A detailed look at the principles of Islamic economics, including risk-sharing, prohibition of interest, and ethical investments, and their application in modern financial systems.",
    "link": "/IslamicEconomics"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Art and Architecture in Andalusia",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the unique contributions of Islamic art and architecture in Andalusia, Spain, and their enduring legacy.",
    "link": "/IslamicAndalusianArt"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Islamic Law in Contemporary Legal Systems",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of how Islamic law (Sharia) is integrated and practiced within contemporary legal systems in various countries.",
    "link": "/IslamicLawInLegalSystems"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Approaches to Mental Health",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of Islamic perspectives on mental health, including traditional and modern approaches to psychological well-being and treatment.",
    "link": "/IslamicMentalHealth"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The History and Development of Islamic Banking",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An overview of the history, principles, and growth of Islamic banking and finance, including key institutions and their global impact.",
    "link": "/IslamicBanking"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Educational Institutions: From Madrasas to Modern Universities",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A review of the evolution of Islamic educational institutions, from traditional madrasas to modern universities, and their contributions to global education.",
    "link": "/IslamicEducation"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Charity in Islam: Beyond Zakat",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of various forms of charity in Islam, including Sadaqah and Waqf, and their role in social welfare and community development.",
    "link": "/IslamicCharity"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Globalization",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of how Islamic teachings and values intersect with the processes and impacts of globalization, including cultural and economic aspects.",
    "link": "/IslamicGlobalization"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Importance of Arabic Language in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the significance of the Arabic language in Islam, its role in the Qur'an and Hadith, and its importance in preserving Islamic heritage.",
    "link": "/ArabicLanguage"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Social Justice",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic principles related to social justice, equity, and the rights of marginalized groups.",
    "link": "/IslamicSocialJustice"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Rizq: Sustenance and Provision in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the Islamic concept of Rizq (sustenance), its sources, and how Muslims understand and seek God's provision.",
    "link": "/ConceptOfRizq"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Responses to Modern Ethical Dilemmas",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on how Islamic ethics address contemporary issues such as bioethics, environmental ethics, and technological advancements.",
    "link": "/IslamicEthicalDilemmas"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Peace and Conflict Resolution",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic teachings on peace, conflict resolution, and reconciliation, and their application in contemporary conflicts.",
    "link": "/IslamicPeaceResolution"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Heritage and Preservation of Sacred Sites",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the significance of Islamic heritage sites, efforts to preserve them, and the challenges faced in their conservation.",
    "link": "/IslamicHeritage"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Poetry in Islamic Culture",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the role and influence of poetry in Islamic culture, including famous poets and their contributions to literature and spirituality.",
    "link": "/IslamicPoetry"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Views on Economic Justice",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the principles of economic justice in Islam, including fair trade, equitable distribution of wealth, and the prohibition of exploitation.",
    "link": "/IslamicEconomicJustice"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Development of Islamic Legal Theory (Usul al-Fiqh)",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the development and principles of Islamic legal theory (Usul al-Fiqh), its methodologies, and its significance in Islamic jurisprudence.",
    "link": "/IslamicLegalTheory"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Approaches to Human Rights",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic perspectives on human rights, their alignment with international human rights standards, and areas of contention.",
    "link": "/IslamicHumanRights"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Technology in Islamic Education",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of how modern technology is being integrated into Islamic education, its benefits, and challenges.",
    "link": "/IslamicTechnologyEducation"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Aging and Elderly Care",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on Islamic teachings related to aging, the respect and care of the elderly, and contemporary issues in elder care.",
    "link": "/IslamicAgingCare"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Call to Prayer (Adhan): Significance and Variations",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the Adhan, its significance, variations in different cultures, and its impact on Muslim communities.",
    "link": "/IslamicAdhan"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Philanthropy and Development",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the role of Islamic philanthropy in development projects, poverty alleviation, and sustainable development in Muslim-majority countries.",
    "link": "/IslamicPhilanthropyDevelopment"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Media and Communication",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An analysis of Islamic teachings related to media ethics, the role of communication in spreading knowledge, and contemporary challenges.",
    "link": "/IslamicMediaCommunication"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Influence of Islamic Jurisprudence on Global Legal Systems",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the influence of Islamic jurisprudence on global legal systems, including common law and civil law traditions.",
    "link": "/IslamicJurisprudenceGlobalLegalSystems"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Festivals and Their Cultural Significance",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of the cultural significance of Islamic festivals, their rituals, and their impact on Muslim communities worldwide.",
    "link": "/IslamicFestivalsCulturalSignificance"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Islamic Scholars in Contemporary Issues",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of the role of Islamic scholars in addressing contemporary issues, providing guidance, and their influence in modern society.",
    "link": "/IslamicScholarsContemporaryIssues"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Concept of Sabr (Patience) in Islam",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of the concept of Sabr, its importance in Islamic teachings, and how it is practiced in daily life.",
    "link": "/IslamicConceptSabr"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Migration and Refugees",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on Islamic teachings related to migration, the treatment of refugees, and the historical context of these issues.",
    "link": "/IslamicMigrationRefugees"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Architecture in Modern Urban Design",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A study of the integration of Islamic architectural principles in modern urban design, and their impact on contemporary cityscapes.",
    "link": "/IslamicArchitectureUrbanDesign"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Influence of Islamic Mysticism on Art and Literature",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of how Islamic mysticism (Sufism) has influenced art and literature, including notable works and figures.",
    "link": "/IslamicMysticismArtLiterature"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on Gender Roles in the Family",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the roles and responsibilities of men and women in the Islamic family structure, and contemporary debates on gender equality.",
    "link": "/IslamicGenderRolesFamily"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Teachings on Health and Wellness",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An examination of Islamic teachings related to health, wellness, and holistic living, including diet, exercise, and mental health.",
    "link": "/IslamicHealthWellness"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "Islamic Perspectives on War and Peace",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "An exploration of Islamic teachings on the ethics of war and peace, including the principles of just war and conflict resolution.",
    "link": "/IslamicWarPeace"
  },
  {
    "date": "13",
    "time": "May",
    "smallHeading": "QURAN EDUCATION",
    "mainHeading": "The Role of Islamic Law in Global Governance",
    "picture": "/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg",
    "name": "BINSAADI.COM",
    "icon": "/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png",
    "description": "A discussion on the influence and application of Islamic law in global governance, international relations, and human rights law.",
    "link": "/IslamicLawGlobalGovernance"
  }
  // Add more objects as needed
];


const NooraniQaida = () => {
  return (
    <div>
      <Layout>
        <div className={styles.container}>
          <main className={styles.mainContent}>
            <div className={styles.CourseseHeading}>
            <FontAwesomeIcon icon={faBlog} className={styles.icon} />
            <h5>Blog</h5>
             </div>
             <div className={styles.MainContentArea}>
             <div>
      <BlogContent content={content} />
            </div>      
            </div>
          </main>
          <div><BlogSidebar /></div>
        </div>
      </Layout>
    </div>
  );
};

export default NooraniQaida;

