import styles from '@/styles/pages/blog.module.scss';
import Layout from '../components/headerAndFooter/Layout';
import BlogSidebar from '@/components/BlogSidebar';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBlog } from '@fortawesome/free-solid-svg-icons';
import BlogContent from '@/components/BlogContent';


const content = [
  {
    date: '13',
    time: 'MAY',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Online Quran Memorization Classes',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: 'Whenever Quran memorization is discussed, issues come to mind: How do you memorize the Quran by heart if you do not speak Arabic and li...',
    link: '/link1',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },

  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },

  {
    date: '13',
    time: 'May',
    smallHeading: 'QURAN EDUCATION',
    mainHeading: 'Teachings the Quran to Your Kids',
    picture: '/imges/mosque-and-moon-during-ramadan-uhd-8k-wallpaper.jpg',
    name: 'BINSAADI.COM',
    icon: '/imges/png-transparent-share-icon-computer-icons-button-button-angle-text-monochrome.png',
    description: `How many times has it happened to you? You were praying in a beautiful and calming mosque. The Quran's melodious recitation enraptures ...`,
    link: '/link2',
  },
  // Add more objects as needed
];


const NooraniQaida = () => {
  return (
    <div>
      <Layout>
        <div className={styles.container}>
          <main className={styles.mainContent}>
            <div className={styles.CourseseHeading}>
            <FontAwesomeIcon icon={faBlog} className={styles.icon} />
            <h5>Blog</h5>
             </div>
             <div className={styles.MainContentArea}>
             <div>
      <BlogContent content={content} />
            </div>      
            </div>
          </main>
          <BlogSidebar />
        </div>
      </Layout>
    </div>
  );
};

export default NooraniQaida;

